# Generated by Django 3.0.1 on 2020-01-09 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_solver', '0002_auto_20200109_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='results',
            old_name='date_stamp',
            new_name='stamp',
        ),
    ]
