# Generated by Django 3.0.1 on 2020-01-09 02:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_solver', '0005_results_stamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sudoku_output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('task_selected', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('stamp', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('task_outcome', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Results',
        ),
    ]
