# Generated by Django 3.0.1 on 2020-01-12 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_solver', '0006_auto_20200109_1331'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sudoku_output',
            new_name='Results',
        ),
    ]
