# Generated by Django 3.0.1 on 2020-01-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_solver', '0009_results_stamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='student_name',
        ),
        migrations.AddField(
            model_name='results',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='standard',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='time_taken',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='task_selected',
            field=models.CharField(max_length=50),
        ),
    ]
