# Generated by Django 3.0.1 on 2020-01-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_solver', '0010_auto_20200114_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='task1_selection',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='task2_colour',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='task2_selection',
            field=models.IntegerField(null=True),
        ),
    ]
