# Generated by Django 3.0.1 on 2020-01-16 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_solver', '0011_auto_20200115_0748'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='favorite',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='subjects',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='age',
            field=models.CharField(max_length=10),
        ),
    ]
