# Generated by Django 3.0.1 on 2020-02-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_solver', '0012_auto_20200116_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='age_2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='favorite_2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='gender_2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='standard_2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='subjects_2',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='token',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
