# Generated by Django 3.0.1 on 2020-02-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_solver', '0013_auto_20200210_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='hobb',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='hobb_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='subjects',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='results',
            name='subjects_2',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
