# Generated by Django 3.0.5 on 2020-08-11 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sudoku_solver', '0014_auto_20200225_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='results',
            name='age_2',
        ),
        migrations.RemoveField(
            model_name='results',
            name='favorite_2',
        ),
        migrations.RemoveField(
            model_name='results',
            name='gender_2',
        ),
        migrations.RemoveField(
            model_name='results',
            name='hobb_2',
        ),
        migrations.RemoveField(
            model_name='results',
            name='standard_2',
        ),
        migrations.RemoveField(
            model_name='results',
            name='subjects_2',
        ),
    ]
