# [START django_app]
runtime: python37
#env: flex
#entrypoint: gunicorn -b :$PORT sudoku.wsgi

#runtime_config:
 # python_version: 3.7

instance_class: B2
basic_scaling:
  max_instances: 4
#
#env_variables:
  #CLOUD_SQL_CONNECTION_NAME: gender-innovation:australia-southeast1:gender-innovation
  #DB_USER: root
  #DB_PASS: cloudadmin
  #sDB_NAME: Project_Results

#beta_settings:
  # for Cloud SQL, set this value to the Cloud SQL connection name,
  # e.g. "project:region:cloudsql-instance"
  #cloud_sql_instances: gender-innovation:australia-southeast1:gender-innovation

handlers:
# This configures Google App Engine to serve the files in the app's static
# directory.
- url: /static
  static_dir: static/


# This handler routes all requests not caught above to your main app. It is
# required when static routes are defined, but can be omitted (along with
# the entire handlers section) when there are no static files defined
- url: /.*
  script: auto

#- url: /
 # static_files: sudoku_solver/templates/sudoku_solver/homepage.html
  #upload: sudoku_solver/templates/sudoku_solver/homepage.html
# [STOP django_app]